### ISSUE TITLE
Citations not working

### ISSUE THREAD

**Issue by fritzbayer** [mcmanigle/OxThesis#3]
The citations in the given file do not work. 

I assume this is not a problem of my computer as the bibliography is also not listed in the given PDF on Github.

**Comment by mcmanigle** [comment]
There are a couple of different processing programs that "do" bibliographies in LaTeX.  Some of the more popular are with bibtex and biber.  Some of the differences are described here: https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib

This template is currently designed to use biber, since it is growing in popularity and is easier to make custom changes to without learning a whole new language. Most LaTeX packages should have an option to run biber, but more technical advice can be found here: https://tex.stackexchange.com/questions/26516/how-to-use-biber

Of course, if you prefer natbib (the older / more traditional way of doing things) feel free to modify the template as necessary, particularly around lines 47-57.

Since merging #4 , the PDF is displayed appropriately for a biber compilation.
