### ISSUE TITLE
How to change bibliography style?

### ISSUE THREAD

**Issue by ealashwali** [mcmanigle/OxThesis#5]
Hi. Thanks for the template. I need to use IEEE bibliography style. My `.bib `file name is` references`. I have the `IEEEtran` `.sty` and `.bst `files in the document to be compiled. I replaced the the following existing bibliography lines:
```
\usepackage[style=numeric, sorting=none, backend=bibtex, doi=false, isbn=false]{biblatex}
\addbibresource{references}
```

with:

```
\bibliographystyle{IEEEtran}
\bibliography{references}
```

But I get errors:
```
\bibfont undefined. \renewcommand*{\bibfont}
Undefined control sequence. \printbibliography
No file Oxford_Thesis.bbl.
Citation `preece1994human' on page 1 undefined
There were undefined references.
```

Can you please clarify how to use IEEE bibliography style in your template?

**Comment by mcmanigle** [comment]
There are a couple of different processing programs that "do" bibliographies in LaTeX. Some of the more popular are with bibtex and biber. Some of the differences are described here: https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib

This template is currently designed to use biber, since it is growing in popularity and is easier to make custom changes to without learning a whole new language. Most LaTeX packages should have an option to run biber, but more technical advice can be found here: https://tex.stackexchange.com/questions/26516/how-to-use-biber

Of course, if you prefer natbib (the older / more traditional way of doing things) feel free to modify the template as necessary, particularly around lines 47-57.
